window.storyFormat({
  "name":"TwingeX",
  "version":"0.1",
  "author":'Ben (that guy) Winding',
  "description":"The extremely simple 'twingex' format.",
  "image":"icon.svg",
  "url":"http://github.com/benwinding/twingex/",
  "license":'MIT License',
  "proofing":false,
  "source":"<html>\r\n\t<head>\r\n\t\t<title>{{STORY_NAME}}</title>\r\n\t\t<meta charset=\"UTF-8\">\r\n\t\t<script type=\"text/javascript\">\r\n\r\nwindow.onload=function(){if(typeof(window.TwingeX)==\"undefined\"){window.Entweedle={convert:function(){var output=window.document.getElementById(\"output\");output.innerHTML=this.export();},export:function(){var buffer=[];var storyData=window.document.getElementsByTagName(\"tw-storydata\");if(storyData){buffer.push(this.buildPassage(\"StoryTitle\",\"\",storyData[0].getAttribute(\"name\")));}\nvar userScript=window.document.getElementById(\"twine-user-script\");if(userScript){buffer.push(this.buildPassage(\"UserScript\",\"script\",userScript.innerHTML));}\nvar userStylesheet=window.document.getElementById(\"twine-user-stylesheet\");if(userStylesheet){buffer.push(this.buildPassage(\"UserStylesheet\",\"stylesheet\",userStylesheet.innerHTML));}\nvar passages=window.document.getElementsByTagName(\"tw-passagedata\");for(var i=0;i<passages.length;++i){buffer.push(this.buildPassageFromElement(passages[i]));}\nreturn buffer.join('');},buildPassageFromElement:function(passage){var name=passage.getAttribute(\"name\");if(!name){name=\"Untitled Passage\";}\nvar tags=passage.getAttribute(\"tags\");var content=passage.textContent;return this.buildPassage(name,tags,content);},buildPassage:function(title,tags,content){var result=[];result.push(\":: \",title);if(tags){result.push(\"[\",tags,\"]\");}\nresult.push(\"\\r\\n\",this.scrub(content),\"\\r\\n\\r\\n\");return result.join('');},scrub:function(content){if(content){content=content.replace(/^::/gm,\" ::\");content=content.replace(/\\</gm,\"&lt;\");content=content.replace(/\\>/gm,\"&gt;\");}\nreturn content;}}}\nwindow.Entweedle.convert();}\t\t\r\n\t\t</script>\r\n\t</head>\r\n\t<body>\r\n\t\t<pre id=\"output\">\r\n\t\t\r\n\t\t</pre>\r\n\t\t<div id=\"storyData\" style=\"display: none;\">\r\n\t\t\t{{STORY_DATA}}\r\n\t\t</div>\r\n\t</body>\r\n</html>"
});